### ISSUE TITLE
Deleting versions and garbage collecting

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#143]
Eventually we will need to have a way to delete old versions and delete raw chunks which are no longer used.

Consider a dataset which gets updated every day such that every value changes. The space usage will grow linearly with the number of versions. Eventually we want to be able to drop versions older than, say, one year, to save some storage space. Just deleting versions is probably easy (?), but the raw chunks would currently still be kept around. So we'd need to identify all now unreferenced chunks and remove them from raw_data.

This is (for now) a low priority, nice to have issue.

**Comment by asmeurer** [comment]
I think we are going to need a way to replay a bunch of versions to recreate the raw data for all of them. This would make it possible to fix a large number of issues, including this one, the ability to change certain metadata like the chunk size (https://github.com/deshaw/versioned-hdf5/issues/110), compression, and number of dimensions, and it would make some of the ideas from https://github.com/deshaw/versioned-hdf5/issues/47 more tenable as well. This would most likely be a relatively expensive operation but it should be something that you would only do rarely.

**Comment by ArvidJB** [comment]
> I think we are going to need a way to replay a bunch of versions to recreate the raw data for all of them.

Let's do this proposal. Should we open a separate issue for this to track it?

**Comment by asmeurer** [comment]
Sure, I opened https://github.com/deshaw/versioned-hdf5/issues/146 for it.

**Comment by asmeurer** [comment]
A useful feature would be to separate the deleting of a version from the garbage collection. The former is just a question of deleting the version group, and would be very cheap to do, whereas the latter require the replaying (https://github.com/deshaw/versioned-hdf5/issues/146) to delete the chunks unique to that version from the raw dataset. One could also move rather than delete the group if one simply wants to prevent Versioned HDF5 from seeing the version, but doesn't want to delete the data or make it inaccessible just yet (being aware that on the next replay operation, the data for that version will be removed and the old version group would most likely point to incorrect chunks and become corrupted).
