### ISSUE TITLE
get_version_by_timestamp is slow when datetime is passed

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#170]
In a file with lots of versions the code in `get_version_by_timestamp` is fairly slow:
```
from __future__ import absolute_import, division

import datetime

import h5py

import numpy as np
from   versioned_hdf5           import VersionedHDF5File

with h5py.File('foo.h5', 'w') as f:
    # create lots of versions
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        sv.create_dataset('bar', data=np.random.rand(10))

    for i in range(1, 1000):
        with vf.stage_version(str(i)) as sv:
            sv['bar'][:] = np.random.rand(10)

with h5py.File('foo.h5', 'r') as f:
    vf = VersionedHDF5File(f)
    versions = f['_version_data/versions']
    version_names = versions.keys()
    dt_fmt = '%Y-%m-%d %H:%M:%S.%f%z'
    timestamps = [datetime.datetime.strptime(versions[v].attrs['timestamp'], dt_fmt)
                  for v in version_names]
    for timestamp in timestamps:
        vf[np.datetime64(timestamp)]['bar'][:]
```
It's slow because it always iterates through all the versions. Is it possible to do a binary search here?

**Comment by asmeurer** [comment]
This code is also failing for me

```pytb
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "./versioned_hdf5/api.py", line 109, in __getitem__
    return self.get_version_by_timestamp(item)
  File "./versioned_hdf5/api.py", line 94, in get_version_by_timestamp
    version = get_version_by_timestamp(self.f, timestamp, exact=exact)
  File "./versioned_hdf5/versions.py", line 209, in get_version_by_timestamp
    raise KeyError(f"Version with timestamp before {timestamp} not found")
KeyError: 'Version with timestamp before 2021-04-05T19:17:52.720144 not found'
```

**Comment by ArvidJB** [comment]
I actually never ran that to completion... It looks like we need to exclude '__first_version__' from the loop.

**Comment by ArvidJB** [comment]
Looks like this was interpreted as markdown. I meant `__first_version__`.

**Comment by asmeurer** [comment]
Yeah, I see now. The `__first_version__` is never supposed to be accessed. The code assumes that every version has a previous version, which is why `__first_version__` exists in the first place.

The issue is that you are using `f['_version_data/versions'].keys()` to get the list of versions, but you should use `list(vf)` instead.

**Comment by asmeurer** [comment]
In general, code outside of the versioned_hdf5 library should be accessing the `_version_data` group. If there's some operation that can't be done without accessing it directly, we should add it to the VersionedHDF5File API.

**Comment by ArvidJB** [comment]
> The issue is that you are using `f['_version_data/versions'].keys()` to get the list of versions, but you should use `list(vf)` instead.
Thanks, I will keep that in mind.

Note that the performance problem does not depend on us iterating over the versions. As long as there are many versions causing the iteration in `get_version_by_timestamp` to not get aborted too early because of a direct match this will be slow.

**Comment by asmeurer** [comment]
I found a simple fix that cuts the time in half, which I've pushed to https://github.com/deshaw/versioned-hdf5/pull/168.

Is your typical use case to access a lot of timestamps at once like this, or is this just to demonstrate the problem? It looks like the bulk of the time is spend looking up the timestamps on the group attrs. This is done every time in the outer loop, and h5py does not seem to cache attribute lookups. We could add some sort of caching, which would help this benchmark, but it wouldn't affect just looking up a single timestamp. Each timestamp access loops through all the groups until it finds a match. This makes the full loop over all versions quadratic in the number of versions, because looking up a single timestamp is linear in the number of versions.

Another option would be to store the timestamps in a single array, rather than (or perhaps in addition to) an attr for each group . This would make lookups faster and would also enable doing a binary search. Right now binary search isn't possible because the version groups aren't sorted by timestamp.

**Comment by ArvidJB** [comment]
The example I came up with is perhaps not the best to show what we are doing. We don't really need to iterate over the versions.
Here's a simpler example to demonstrate how it is slow to read a version for a timestamp when there are lots of versions:
```
with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        dt = np.datetime64('now')
        sv.create_dataset('bar', data=np.random.rand(10))

    for i in range(1, 1000):
        with vf.stage_version(str(i)) as sv:
            dt = np.datetime64('now')
            sv['bar'][:] = np.random.rand(10)

with h5py.File('foo.h5', 'r') as f:
    vf = VersionedHDF5File(f)
    for _ in range(1000):
        _ = vf[dt]['bar'][:]
```

**Comment by asmeurer** [comment]
I see. That's effectively the same, though, because each `vf[dt]` has to search for the version again. We can cache the result so that it only has to find it once.

**Comment by asmeurer** [comment]
I pushed a change to https://github.com/deshaw/versioned-hdf5/pull/168 that does that. Your example now runs at the same speed as if you replace `vf[dt]` with `vf[str(i)]`.
