### ISSUE TITLE
Large overhead due to _add_to_data

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#217]
Reading many small arrays from a versioned HDF5 file it is a lot slower compared to a regular HDF5 file. Most of the overhead is due to `InMemoryGroup._add_to_data` being called in `InMemoryGroup__getitem__`. For example the code below takes 15-16 seconds with `versioned_hdf5` and only around 2 seconds without versioning:
```
    n = 100
    with h5py.File('foo.h5', 'w') as f:
        vf = VersionedHDF5File(f)
        with vf.stage_version('r0') as sv:
            for i in range(n):
                sv.create_dataset(f'data/values/{i}', data=np.arange(4))

    for _ in range(100):
        with h5py.File('foo.h5', 'r') as f:
            vf = VersionedHDF5File(f)
            cv = vf[vf.current_version]
            for i in range(n):
                _ = cv[f'data/values/{i}'][:]
```

It seems like in `_add_to_data` we get the Dataset for `raw_data` just to get the compression. Is this code really necessary? Can we get the compression lazily? If that's difficult, can we make this faster by not constructing the Dataset for `raw_data` just to get the compression?

**Comment by asmeurer** [comment]
I think we can make reading faster in cases where the dataset is read-only (not in a `stage_version` block) by bypassing most of the wrapper classes that are only needed to keep track of changes. Is this also a concern inside of stage_version blocks?

**Comment by ArvidJB** [comment]
We are mainly worried about read performance, so it's probably fine to optimize for only that.

**Comment by asmeurer** [comment]
Here is what I have so far:

- If the file is read-only (opened with `'r'`), we can completely bypass the versioned_hdf5 wrapper classes and return the versioned group class directly. This seems to work and is faster. This has a few potential downsides however:

  - This breaks support for mask indices because we have been supporting those manually (https://github.com/deshaw/versioned-hdf5/issues/201). Note that this does appear to be implemented in newer versions of h5py, so it's only a problem for h5py 2.10.
  - If any code is relying on internal details of the wrapper classes (InMemoryGroup, InMemoryDataset, and so on), it will not work in this case, because it will just get normal h5py Group and Dataset objects.

- If the file is *not* read-only, but the group itself is read-only (not in a `stage_version` block), doing this would completely bypass the safety checks that prevent accidentally writing directly into a versioned dataset (which would corrupt the underlying raw data). There's no way to have these safety checks in pure h5py; they have to be done in the wrapper classes. So I would prefer not to do this. It does mean that there could be subtle performance differences between reading data in a read-only file vs. a read/write file. If this is important, I can look into whether the performance of the wrapper classes can be improved directly. 

The only failure in the test suite is the one relating to masks, but I'm not confident that the test suite would catch everything as most tests don't open the file in read-only mode. So we should try to do some more testing, and you may want to check this on your own test suite.

A preliminary pull request implementing the above is at https://github.com/deshaw/versioned-hdf5/pull/218

**Comment by asmeurer** [comment]
> Sounds promising. The good news is that we have finally moved off h5py version 2.10 (we are now on version 3.6). 

OK. I think I'll leave 2.10 support there for now (I've made the masking test XFAIL in h5py 2.10). If we ever do any major refactors or changes in the future we may want to just drop 2.10 support to make things easier. 

> as far as I know, we only write to a versioned Dataset in a stage_version block, but obviously I cannot be 100% sure.

Well right now there are safety checks so you shouldn't be. If you try it you'll get an error. But if we completely bypass the wrapper classes those safety checks would be removed and you wouldn't be protected from an accidental write (of course you can still bypass it manually by just using h5py and ignoring versioned_hdf5, but that would mean intentionally digging into the `_versioned_data` group).

**Comment by asmeurer** [comment]
> OK. I think I'll leave 2.10 support there for now (I've made the masking test XFAIL in h5py 2.10). If we ever do any major refactors or changes in the future we may want to just drop 2.10 support to make things easier.

We should also make sure we always have a build on CI for the version you are using. Right now 3.6 is the latest version so this isn't a concern yet.
