### ISSUE TITLE
Support writing strings in versioned file (shape 0 arrays)

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#24]
In h5py you can write strings/bytes directly to a file:
```
In [1]: import h5py

In [2]: with h5py.File('foo.h5', 'w') as f:
   ...:     f['bar'] = b'baz'
   ...:

In [3]: with h5py.File('foo.h5', 'r') as f:
   ...:     print(f['bar'][()])
   ...:
b'baz'
```
Note that the "shape" is an empty tuple.
We should add support for this in versioned-hdf5.

**Comment by asmeurer** [comment]
Assigning bytes strings should now work, just as with #26, since we now use np.asarray. The issue here though is that we don't support shape 0 arrays. This should be considered as part of multidimensional array support, since most places in versioned-hdf5 currently have single dimension hard-coded.

**Comment by melissawm** [comment]
An update on this issue and PR #96 :

While trying to investigate the failure to create a second version as pointed out in the comments of PR #96, I found out that there is a HDF5 bug related to scalar datasets: https://github.com/h5py/h5py/issues/1409

The origin of the problem was the VirtualSource/VirtualLayout linking; since both were created with the same shape as the data, in this case a shape-0 array, the virtual dataset was not being created properly. As a workaround I increased the shapes for the VirtualSource/VirtualLayout objects, while keeping the original data with shape 0. This works if we access the data via Versioned HDF5, but not via h5py. This is in #96 

As I understand it, here's what's happening:
- Creating a shape-0 **dataset** works in h5py (see above)
- Creating a shape-0 **virtual dataset** does not work in h5py (see https://github.com/h5py/h5py/issues/1409)


Example:

```python
In [1]: import h5py; from versioned_hdf5 import VersionedHDF5File                                   

In [2]: f = h5py.File('test.h5', 'w'); file = VersionedHDF5File(f)                                  

In [3]: with file.stage_version('version1') as group: 
   ...:     group['scalar_ds'] = b'baz' 
   ...:                                                                                             

In [4]: file['version1']['scalar_ds']                                                               
Out[4]: <InMemoryArrayDataset "scalar_ds": shape (), type "|S3">

In [5]: file['version1']['scalar_ds'][()]                                                           
Out[5]: b'baz'

In [6]: f['_version_data/versions']['version1']['scalar_ds']                                        
Out[6]: <HDF5 dataset "scalar_ds": shape (1,), type "|S3">

In [7]: f['_version_data/versions']['version1']['scalar_ds'][()]                                    
Floating point exception (core dumped)
```

**Comment by asmeurer** [comment]
I think as a workaround we can just copy scalar datasets instead of making them virtual. Since they are scalars, it shouldn't affect the file size too much. There are some places in the code that expect a dataset to be virtual that would need to be modified to handle this.

**Comment by asmeurer** [comment]
This should work now. Let us know if you still have issues with this.
