### ISSUE TITLE
Get airspeed velocity benchmarks working again (PyInf#12733)

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#343]
Not sure when the benchmarks stopped working...
We used to automatically populate https://deshaw.github.io/versioned-hdf5/benchmarks on every commit by running [airspeed velocity](https://github.com/airspeed-velocity/asv).

Let's get this working again!

Also, we may want to update the benchmarks
https://deshaw.github.io/versioned-hdf5/master/performance.html
All of this is probably much faster now?

**Comment by asmeurer** [comment]
The benchmarks were never run automatically. I just ran them on my computer every once in a while. asv automatically includes all commits when you run it. It's hard to run long term benchmarks on CI because you can't really be sure you have a consistent runtime across runs.

**Comment by asmeurer** [comment]
You can use CI to run a comparison benchmark between the PR and master, because the runs will be consistent for the same runner. We do this in SymPy https://github.com/sympy/sympy/blob/0710d784347042c54270fd562a47317607b9be30/.github/workflows/runtests.yml#L482 https://github.com/sympy/sympy/blob/master/.github/workflows/comment-on-pr.yml

**Comment by peytondmurray** [comment]
@ArvidJB I just filed a request to allow cirun.io permissions for this repo so that we can run benchmarks on AWS. Once we have that enabled, we should be able to do run this quickly.
