### ISSUE TITLE
Move split_slice into ndindex

### ISSUE THREAD

**Issue by melissawm** [deshaw/versioned-hdf5#92]
Right now, `split_slice` is in `slicetools.py`.

**Comment by asmeurer** [comment]
Also `as_subchunks` and `split_chunks`. However, I'm not sure how the API for these should be properly generalized for ndindex, so for now, this remains an open question At least after #72 they are a lot simpler, so the need to move them over is much less, since most of the actual logic is already in ndindex and they are written using high-level ndindex functions.

**Comment by asmeurer** [comment]
This is now part of ndindex.ChunkSize. slicetools now only contains tools specific to converting to and from h5py spaceid objects.
